// {{ comment_title }}: {{ cols }}x{{ rows }} text-mode art. Generated by acidtrip.
import * as React from "react";

const COLORS: string[] = {{ colors }};

// One entry per line: [text, fg, bg] runs (bg -1 = transparent).
const LINES: [string, number, number][][] = {{ lines }};

const FONT = {{ font_stack }};

export function {{ ident }}(props: { className?: string; scale?: number; style?: React.CSSProperties }) {
  const scale = props.scale ?? 1;
  const style: React.CSSProperties = {
    margin: 0,
    display: "inline-block",
    color: COLORS[{{ default_fg }}],
    background: {{ background }},
    fontFamily: FONT,
    fontSize: `${16 * scale}px`,
    lineHeight: 1,
    letterSpacing: 0,
    whiteSpace: "pre",
    ...props.style,
  };
  return (
    <pre className={props.className} style={style} aria-label={ {{- title -}} }>
      {LINES.map((runs, y) => (
        <React.Fragment key={y}>
          {runs.map(([text, fg, bg], i) => (
            <span key={i} style={{ "{{" }} color: COLORS[fg], background: bg < 0 ? undefined : COLORS[bg] {{ "}}" }}>
              {text}
            </span>
          ))}
          {"\n"}
        </React.Fragment>
      ))}
    </pre>
  );
}

export default {{ ident }};
